### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by krober10nd** [pygridgen/pygridgen#56]
* Built `pygridgen` via the conda recipe. 
* When I go to run, it can't find a symbol in the shared library. 
```
import numpy
x = numpy.array([0.5, 2.0, 2.5, 1.5, 0.5])
y = numpy.array([0.5, 0.5, 2.0, 2.0, 0.5])
beta = numpy.array([1, 1, 1, 1, 0])
rows = 10
cols = 5
grid = pygridgen.Gridgen(x, y, beta, shape=(rows, cols))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/kroberts/codes/pygridgen/pygridgen/grid.py", line 813, in __init__
    self._libgridgen.gridgen_generategrid2.restype = ctypes.POINTER(ctypes.c_void_p)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libgridgen.so: undefined symbol: gridgen_generategrid2
```

**Comment by krober10nd** [comment]
Myshared library contains `gridgen_generategrid` but not `gridgen_generategrid2`. 

``` 
nm -D /usr/local/lib/libgridgen.so
```

**Comment by phobson** [comment]
Which conda recipe did you use?

**Comment by krober10nd** [comment]
This one https://pygridgen.readthedocs.io/en/latest/install/conda.html

I also got the same error building from source for Linux.

**Comment by ocefpaf** [comment]
> This one https://pygridgen.readthedocs.io/en/latest/install/conda.html

@krober10nd are you building it yourself or installing a pre-built binary from conda-forge? The instructions there are to install it and they use Python 3.6, which is deprecated and probably will not work with latest packages.

> I also got the same error building from source for Linux.

We cannot help you unless we know all the versions of all the dependencies.  If you can use a pre-built binary this works for me:

```shell
conda create --name=grid python=3.7 pygridgen --channel=conda-forge
conda activate grid
```

**Comment by krober10nd** [comment]
Sorry what? I just showed you the conda recipe I used. 

Why is python 3.6 deprecated? 

I then tried to build by source. 
I followed the instructions on your readthedocs for building it by source. Neither worked with the error above.

**Comment by ocefpaf** [comment]
> Sorry what? I just showed you the conda recipe I used.

Nope. The link in https://github.com/pygridgen/pygridgen/issues/56#issuecomment-999118355 is for instructions to install it with conda. A conda recipe would be something like this:

https://github.com/conda-forge/pygridgen-feedstock/blob/master/recipe/meta.yaml

> Why is python 3.6 deprecated?

For scientific stack the end of life was Jan 2017. See https://numpy.org/neps/nep-0029-deprecation_policy.html

For the General Python users it is today. See https://endoflife.date/python

> I followed the instructions on your readthedocs for building it by source. Neither worked with the error above.

As I said above, to help you with that we are going to need more info. Like what versions of the dependencies, how you are building them, etc. The stack is a bit complicated and that is why we recommend a pre-built binary with a modern Python.
